import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/feed'
import Footer from '../components/footer'
import Login from '../components/login'
import styles from '../styles/Home.module.css'
import { getProviders, getSession, useSession } from "next-auth/react";

export default function Home({ trendingResults, followResults, providers }) {
  const { data: session } = useSession();
  if(!session)return <Login providers={providers}/>
  return (
    <div>
      <Head>
        <title>Instagram copy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Feed/>
    </div>
  )
}


export async function getServerSideProps(context) {
  const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}
